// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5D30dOe4XP6ghyNcE1Kqqg7WhMn0ugEk',
    appId: '1:531800012003:web:88f49e63836f6bcd7d01d6',
    messagingSenderId: '531800012003',
    projectId: 'unimatcher-1f723',
    authDomain: 'unimatcher-1f723.firebaseapp.com',
    storageBucket: 'unimatcher-1f723.appspot.com',
    measurementId: 'G-K7CJJZ2GNZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnUJvQO9i6bh27-xVAf2fm4gjHFfrjvd4',
    appId: '1:531800012003:android:34e3120fb82af3cd7d01d6',
    messagingSenderId: '531800012003',
    projectId: 'unimatcher-1f723',
    storageBucket: 'unimatcher-1f723.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdz9BuZmxEoCB-0-GbM2or4dFRk9JVTaU',
    appId: '1:531800012003:ios:08de12f81c9f2af47d01d6',
    messagingSenderId: '531800012003',
    projectId: 'unimatcher-1f723',
    storageBucket: 'unimatcher-1f723.appspot.com',
    androidClientId:
        '531800012003-f269n4iaff8aopcj3g026adb1f6v36pd.apps.googleusercontent.com',
    iosClientId:
        '531800012003-pdac7tboi187bjc8fkepn090armjupl0.apps.googleusercontent.com',
    iosBundleId: 'com.example.unimatcherAdmin',
  );
}
